# Generated by Django 5.1 on 2024-11-13 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_course_options"),
        ("study", "0003_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_marks",
                to="core.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_marks",
                to="core.teacher",
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="value",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
