# Generated by Django 5.1 on 2024-11-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_course_options"),
        ("study", "0004_alter_mark_student_alter_mark_teacher_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Mark",
            new_name="MarkLesson",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="study_group",
            new_name="group",
        ),
    ]
