# Generated by Django 5.1 on 2024-11-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Отчество"
            ),
        ),
    ]
