# Generated by Django 5.1 on 2024-11-13 09:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_studygroup_options_alter_adminhod_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("date_start", models.DateField(verbose_name="Начало сессии")),
                ("date_end", models.DateField(verbose_name="Конец сессии")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия",
                "verbose_name_plural": "Сессии",
            },
        ),
    ]
