# Generated by Django 5.1 on 2024-11-12 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_studygroup_options_alter_adminhod_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationStudent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление студента",
                "verbose_name_plural": "Уведомления студента",
            },
        ),
        migrations.CreateModel(
            name="NotificationTeacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление сотрудника",
                "verbose_name_plural": "Уведомления сотрудника",
            },
        ),
    ]
