# Generated by Django 5.1 on 2024-11-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationstudent_subject_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notificationteacher",
            options={
                "verbose_name": "Уведомление преподавателя",
                "verbose_name_plural": "Уведомления преподавателя",
            },
        ),
    ]
