# Generated by Django 5.1 on 2024-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationteacher_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationstudent",
            name="subject",
            field=models.CharField(
                choices=[
                    ("homework", "Домашняя работа проверена"),
                    ("suggestion", "Предложение"),
                    ("complaint", "Жалоба"),
                    ("message", "Новое входящее сообщение"),
                    ("session", "Сессия"),
                    ("exam", "Экзамен"),
                    ("mark", "Оценка"),
                    ("feedback", "Ваше обращение принято"),
                    ("subscription", "Вы успешно подписались на рассылку"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="notificationteacher",
            name="subject",
            field=models.CharField(
                choices=[
                    ("homework", "Домашняя работа проверена"),
                    ("suggestion", "Предложение"),
                    ("complaint", "Жалоба"),
                    ("message", "Новое входящее сообщение"),
                    ("session", "Сессия"),
                    ("exam", "Экзамен"),
                    ("mark", "Оценка"),
                    ("feedback", "Ваше обращение принято"),
                    ("subscription", "Вы успешно подписались на рассылку"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=20,
                verbose_name="Тема",
            ),
        ),
    ]
